# Generated by Django 5.2 on 2025-05-06 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.CharField(choices=[('Yellow leaves', 'Yellow leaves'), ('Brown tips', 'Brown tips'), ('Wilting', 'Wilting'), ('Leaf drop', 'Leaf drop'), ('Moldy soil', 'Moldy soil'), ('Leggy growth', 'Leggy growth'), ('Pale leaves', 'Pale leaves'), ('Sticky leaves', 'Sticky leaves'), ('Root rot', 'Root rot'), ('Spots on leaves', 'Spots on leaves')], max_length=255)),
                ('solution', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.URLField(blank=True, max_length=500)),
                ('last_watered', models.DateField()),
                ('watering_frequency_days', models.IntegerField(default=3)),
                ('last_fertilized', models.DateField(blank=True, null=True)),
                ('fertilizing_frequency_days', models.IntegerField(default=14)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('remind_at', models.DateTimeField()),
                ('is_done', models.BooleanField(default=False)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='main_app.plant')),
            ],
        ),
    ]
